export const KEYWORDS_DATA = [
  // SALUDO
  { keyword: 'hola', intention: 'SALUDO' },
  { keyword: 'buenas', intention: 'SALUDO' },
  { keyword: 'buenos dias', intention: 'SALUDO' },
  { keyword: 'buenas tardes', intention: 'SALUDO' },
  { keyword: 'buenas noches', intention: 'SALUDO' },
  { keyword: 'que tal', intention: 'SALUDO' },
  { keyword: 'como estas', intention: 'SALUDO' },
  { keyword: 'saludos', intention: 'SALUDO' },
  { keyword: 'hey', intention: 'SALUDO' },
  { keyword: 'holi', intention: 'SALUDO' },

  // RESERVA
  { keyword: 'reserva', intention: 'RESERVA' },
  { keyword: 'reservar', intention: 'RESERVA' },
  { keyword: 'hacer una cita', intention: 'RESERVA' },
  { keyword: 'turno', intention: 'RESERVA' },
  { keyword: 'agendar', intention: 'RESERVA' },
  { keyword: 'agenda', intention: 'RESERVA' },
  { keyword: 'quiero reservar', intention: 'RESERVA' },
  { keyword: 'necesito una cita', intention: 'RESERVA' },
  { keyword: 'disponibilidad', intention: 'RESERVA' },
  { keyword: 'sacar cita', intention: 'RESERVA' },
  { keyword: 'sacar turno', intention: 'RESERVA' },
  { keyword: 'pedir cita', intention: 'RESERVA' },
  { keyword: 'pedir turno', intention: 'RESERVA' },
  { keyword: 'quiero una cita', intention: 'RESERVA' },
  { keyword: 'quiero un turno', intention: 'RESERVA' },
  { keyword: 'cuando puedo ir', intention: 'RESERVA' },
  { keyword: 'cuando me atienden', intention: 'RESERVA' },
  { keyword: 'hay cupo', intention: 'RESERVA' },
  { keyword: 'hay espacio', intention: 'RESERVA' },
  { keyword: 'cuando hay cita', intention: 'RESERVA' },
  { keyword: 'cuando hay turno', intention: 'RESERVA' },
  { keyword: 'puedo agendar', intention: 'RESERVA' },
  { keyword: 'puedo sacar cita', intention: 'RESERVA' },
  { keyword: 'quiero atenderme', intention: 'RESERVA' },
  { keyword: 'quiero agendar', intention: 'RESERVA' },
  { keyword: 'proxima cita', intention: 'RESERVA' },
  { keyword: 'proximo turno', intention: 'RESERVA' },

  // CANCELAR
  { keyword: 'cancelar mi cita', intention: 'CANCELAR' },
  { keyword: 'cancelar mi turno', intention: 'CANCELAR' },
  { keyword: 'cancelar mi reserva', intention: 'CANCELAR' },
  { keyword: 'cancelar cita', intention: 'CANCELAR' },
  { keyword: 'cancelar turno', intention: 'CANCELAR' },
  { keyword: 'cancelar reserva', intention: 'CANCELAR' },
  { keyword: 'anular cita', intention: 'CANCELAR' },
  { keyword: 'eliminar cita', intention: 'CANCELAR' },
  { keyword: 'borrar reserva', intention: 'CANCELAR' },
  { keyword: 'no puedo ir', intention: 'CANCELAR' },
  { keyword: 'cancelar turno', intention: 'CANCELAR' },
  { keyword: 'no puedo ir', intention: 'CANCELAR' },

  // UBICACION
  { keyword: 'ubicacion', intention: 'UBICACION' },
  { keyword: 'direccion', intention: 'UBICACION' },
  { keyword: 'donde estan', intention: 'UBICACION' },
  { keyword: 'donde queda', intention: 'UBICACION' },
  { keyword: 'donde quedan', intention: 'UBICACION' },
  { keyword: 'localizacion', intention: 'UBICACION' },
  { keyword: 'mapa', intention: 'UBICACION' },
  { keyword: 'google maps', intention: 'UBICACION' },
  { keyword: 'google mapa', intention: 'UBICACION' },
  { keyword: 'como llegar', intention: 'UBICACION' },
  { keyword: 'direccion exacta', intention: 'UBICACION' },
  { keyword: 'sitio', intention: 'UBICACION' },
  { keyword: 'sede', intention: 'UBICACION' },
  { keyword: 'oficina', intention: 'UBICACION' },
  { keyword: 'clinica', intention: 'UBICACION' },

  // HORARIO
  { keyword: 'horario', intention: 'HORARIO' },
  { keyword: 'horarios', intention: 'HORARIO' },
  { keyword: 'atienden', intention: 'HORARIO' },
  { keyword: 'a que hora atienden', intention: 'HORARIO' },
  { keyword: 'a que horas atienden', intention: 'HORARIO' },
  { keyword: 'cuando atienden', intention: 'HORARIO' },
  { keyword: 'cuando abren', intention: 'HORARIO' },
  { keyword: 'cuando cierran', intention: 'HORARIO' },
  { keyword: 'hora de atencion', intention: 'HORARIO' },
  { keyword: 'horas de atencion', intention: 'HORARIO' },
  { keyword: 'están abiertos', intention: 'HORARIO' },
  { keyword: 'está abierto', intention: 'HORARIO' },
  { keyword: 'estan atendiendo', intention: 'HORARIO' },
  { keyword: 'hoy atienden', intention: 'HORARIO' },
  { keyword: 'mañana atienden', intention: 'HORARIO' },
  { keyword: 'horario hoy', intention: 'HORARIO' },

  // DERIVA_MEDICO
  { keyword: 'deriva medico', intention: 'DERIVA_MEDICO' },
  { keyword: 'hablar medico', intention: 'DERIVA_MEDICO' },
  { keyword: 'medico', intention: 'DERIVA_MEDICO' },
  { keyword: 'doctor', intention: 'DERIVA_MEDICO' },
  { keyword: 'operacion', intention: 'DERIVA_MEDICO' },
  { keyword: 'cirujia', intention: 'DERIVA_MEDICO' },
  { keyword: 'urgencia', intention: 'DERIVA_MEDICO' },
  { keyword: 'hablar con el doctor', intention: 'DERIVA_MEDICO' },
  { keyword: 'quiero hablar con el doctor', intention: 'DERIVA_MEDICO' },
  { keyword: 'necesito al doctor', intention: 'DERIVA_MEDICO' },
  { keyword: 'consulta con el doctor', intention: 'DERIVA_MEDICO' },
  { keyword: 'consulta con medico', intention: 'DERIVA_MEDICO' },
  { keyword: 'urgente', intention: 'DERIVA_MEDICO' },
  { keyword: 'emergencia', intention: 'DERIVA_MEDICO' },
  { keyword: 'ayuda urgente', intention: 'DERIVA_MEDICO' },
  { keyword: 'dolor fuerte', intention: 'DERIVA_MEDICO' },
  { keyword: 'dolor intenso', intention: 'DERIVA_MEDICO' },
  { keyword: 'me duele mucho', intention: 'DERIVA_MEDICO' },
  { keyword: 'quirurgia', intention: 'DERIVA_MEDICO' },
  { keyword: 'cirugia', intention: 'DERIVA_MEDICO' },
  { keyword: 'intervencion', intention: 'DERIVA_MEDICO' },
  { keyword: 'evaluacion urgente', intention: 'DERIVA_MEDICO' },


  // GEMINI
  { keyword: 'gemini', intention: 'GEMINI' },
  { keyword: 'recomendacion', intention: 'GEMINI' },
  { keyword: 'ayuda', intention: 'GEMINI' },
  { keyword: 'asistencia', intention: 'GEMINI' },
  { keyword: 'hablar', intention: 'GEMINI' },

  //ESPECIALIDADES
  { keyword: 'especialidades', intention: 'ESPECIALIDADES' },
  { keyword: 'especialidad', intention: 'ESPECIALIDADES' },
  { keyword: 'en que son buenos', intention: 'ESPECIALIDADES' },
  { keyword: 'tiene esta especialidad', intention: 'ESPECIALIDADES' },
  { keyword: 'es bueno', intention: 'ESPECIALIDADES' },
  { keyword: 'que atienden', intention: 'ESPECIALIDADES' },
  { keyword: 'que servicios ofrecen', intention: 'ESPECIALIDADES' },
  { keyword: 'que tratamientos hacen', intention: 'ESPECIALIDADES' },
  { keyword: 'tratamientos', intention: 'ESPECIALIDADES' },
  { keyword: 'servicios', intention: 'ESPECIALIDADES' },
  { keyword: 'atienden esto', intention: 'ESPECIALIDADES' },
  { keyword: 'atienden', intention: 'ESPECIALIDADES' },
  { keyword: 'tienen este tratamiento', intention: 'ESPECIALIDADES' },
  { keyword: 'hacen esto', intention: 'ESPECIALIDADES' },
  { keyword: 'que hacen', intention: 'ESPECIALIDADES' },
  { keyword: 'ofrecen implantologia', intention: 'ESPECIALIDADES' },
  { keyword: 'ofrecen ortodoncia', intention: 'ESPECIALIDADES' },
  { keyword: 'ofrecen rehabilitacion', intention: 'ESPECIALIDADES' },
  { keyword: 'tienen ortodoncia', intention: 'ESPECIALIDADES' },
  { keyword: 'tienen implantologia', intention: 'ESPECIALIDADES' },
  { keyword: 'tienen rehabilitacion', intention: 'ESPECIALIDADES' },

  //PRECIOS
  { keyword: 'precios', intention: 'PRECIOS' },
  { keyword: 'precio', intention: 'PRECIOS' },
  { keyword: 'cuanto cuesta', intention: 'PRECIOS' },
  { keyword: 'a cuanto sale', intention: 'PRECIOS' },
  { keyword: 'me interesa', intention: 'PRECIOS' },
  { keyword: 'costo', intention: 'PRECIOS' },
  { keyword: 'costos', intention: 'PRECIOS' },
  { keyword: 'tarifa', intention: 'PRECIOS' },
  { keyword: 'tarifas', intention: 'PRECIOS' },
  { keyword: 'valor', intention: 'PRECIOS' },
  { keyword: 'valores', intention: 'PRECIOS' },
  { keyword: 'que vale', intention: 'PRECIOS' },
  { keyword: 'cuanto vale', intention: 'PRECIOS' },
  { keyword: 'cuanto me sale', intention: 'PRECIOS' },
  { keyword: 'cuanto cobran', intention: 'PRECIOS' },
  { keyword: 'cuanto cobran por', intention: 'PRECIOS' },
  { keyword: 'precio de', intention: 'PRECIOS' },
  { keyword: 'costo de', intention: 'PRECIOS' },
  { keyword: 'que precio tiene', intention: 'PRECIOS' },
  { keyword: 'es caro', intention: 'PRECIOS' },
  { keyword: 'esta caro', intention: 'PRECIOS' },
  { keyword: 'cuanto seria', intention: 'PRECIOS' },
  { keyword: 'como es el precio', intention: 'PRECIOS' },
  { keyword: 'como es el costo', intention: 'PRECIOS' },


];